quarkus.datasource.db-kind=postgresql

# ¡Pega aquí tu cadena copiada! (Asegúrate de que empiece con jdbc: y traiga tu password visible)
quarkus.datasource.jdbc.url=jdbc:postgresql://ep-rapid-rain-ay2rjkl8-pooler.c-5.us-east-2.aws.neon.tech/neondb?user=neondb_owner&password=npg_lS0ij1yvKEQo&sslmode=require&channelBinding=require

# La línea para que se creen las tablas
quarkus.hibernate-orm.database.generation=update