# ========================================================
# CONFIGURACIÓN DE BASE DE DATOS (POSTGRESQL)
# ========================================================

quarkus.datasource.db-kind=postgresql
quarkus.datasource.jdbc.url=jdbc:postgresql://localhost:5432/inventario_setab
quarkus.datasource.username=postgres
quarkus.datasource.password=PoSGret18
quarkus.hibernate-orm.database.generation=update

# --- VARIABLES PARA LA NUBE (RENDER) ---
%prod.quarkus.datasource.jdbc.url=jdbc:postgresql://dpg-db1t8op7lnhs73edrvl0-a.oregon-postgres.render.com:5432/setab_bd_frfm
%prod.quarkus.datasource.username=setab_bd_frfm_user
%prod.quarkus.datasource.password=kNcGFmc7SMh2hFLDSYgNeU1MMoC4CmVe

quarkus.http.host=0.0.0.0



# ========================================================
# CONFIGURACIÓN DE SEGURIDAD CON KEYCLOAK (OIDC)
# ========================================================

quarkus.oidc.auth-server-url=http://192.168.137.220:8081/realms/setab-erp
quarkus.oidc.client-id=setab-frontend
quarkus.oidc.application-type=service

# --- SEGURIDAD PARA LA NUBE (LEMUR IAM) ---
%prod.quarkus.oidc.auth-server-url=https://lemur-17.cloud-iam.com/auth/realms/setab-erp

quarkus.oidc.token.issuer=any
quarkus.oidc.token.principal-claim=preferred_username
quarkus.oidc.roles.role-claim-path=realm_access/roles



# ========================================================
# DEBUG DE SEGURIDAD
# ========================================================
quarkus.log.category."io.quarkus.security".level=DEBUG
quarkus.log.category."io.quarkus.oidc".level=DEBUG

# ========================================================
# CONFIGURACIÓN DEL CLIENTE ADMIN DE KEYCLOAK (PRODUCCIÓN)
# ========================================================

keycloak.admin.server-url=http://192.168.137.220:8081
keycloak.admin.realm=master
keycloak.admin.client-id=admin-cli
keycloak.admin.username=admin
keycloak.admin.password=admin

# --- CLIENTE ADMIN PARA LA NUBE ---
%prod.keycloak.admin.server-url=https://lemur-17.cloud-iam.com/auth
%prod.keycloak.admin.realm=master
%prod.keycloak.admin.client-id=admin-cli
%prod.keycloak.admin.username=Admin
%prod.keycloak.admin.password=r@3/DGf1EucT;Vy5u.qK

# --- CLIENTE ADMIN PARA LA NUBE ---
%prod.keycloak.admin.server-url=https://lemur-17.cloud-iam.com/auth

# ========================================================
# CONFIGURACIÓN DE CORS (PERMISOS PARA EL FRONTEND)

# ========================================================

quarkus.http.cors=true
quarkus.http.cors.origins=https://setabinventarios.vercel.app,http://127.0.0.1:5500,http://localhost:5500,http://localhost:8080
quarkus.http.cors.methods=GET, PUT, POST, DELETE, OPTIONS
quarkus.http.cors.headers=accept, authorization, content-type, x-requested-with

